apiVersion: apps/v1

kind: Deployment
metadata:
  name: go-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
      - name: go-app-container
        image: zeroacrdemo.azurecr.io/zero-go-azure-demo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-world-service
spec:
  selector:
    app: go-hello-world
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer